"""Configuration constants for the Redrob candidate ranker."""

from __future__ import annotations

from datetime import date

REFERENCE_DATE = date(2026, 6, 4)

TIER1_INDIA_CITY_KEYWORDS = (
    "pune",
    "noida",
    "delhi",
    "gurgaon",
    "gurugram",
    "bangalore",
    "bengaluru",
    "hyderabad",
    "mumbai",
    "chennai",
)

PREFERRED_COUNTRY = "india"

HIGH_SIGNAL_TITLES = (
    "ai engineer",
    "ml engineer",
    "machine learning engineer",
    "senior machine learning engineer",
    "junior ml engineer",
    "nlp engineer",
    "search engineer",
    "relevance engineer",
    "ranking engineer",
    "recommendation engineer",
    "data scientist",
    "applied scientist",
    "research engineer",
)

ADJACENT_SIGNAL_TITLES = (
    "software engineer",
    "senior software engineer",
    "backend engineer",
    "data engineer",
    "senior data engineer",
    "analytics engineer",
    "full stack developer",
    "java developer",
    "frontend engineer",
    "cloud engineer",
    "devops engineer",
)

NON_TECHNICAL_TITLES = (
    "marketing manager",
    "hr manager",
    "accountant",
    "content writer",
    "sales executive",
    "graphic designer",
    "mechanical engineer",
    "civil engineer",
    "customer support",
    "operations manager",
    "project manager",
    "business analyst",
)

CONSULTING_COMPANIES = {
    "tcs",
    "infosys",
    "wipro",
    "accenture",
    "cognizant",
    "capgemini",
    "hcl",
    "tech mahindra",
    "mindtree",
    "ltimindtree",
    "ibm consulting",
}

PRODUCT_BRANDS = {
    "google",
    "meta",
    "amazon",
    "microsoft",
    "flipkart",
    "swiggy",
    "zomato",
    "uber",
    "ola",
    "paytm",
    "freshworks",
    "razorpay",
    "meesho",
    "linkedin",
    "atlassian",
    "netflix",
    "airbnb",
    "spotify",
    "phonepe",
    "byju's",
    "upgrad",
}

PRODUCT_INDUSTRY_KEYWORDS = (
    "software",
    "saas",
    "e-commerce",
    "fintech",
    "marketplace",
    "recruit",
    "hr tech",
    "hr-tech",
    "adtech",
    "edtech",
    "consumer",
    "food delivery",
    "transportation",
    "insurance tech",
    "gaming",
    "ai/ml",
    "conversational ai",
)

STARTUP_SIZE_BUCKETS = {"1-10", "11-50", "51-200"}

RELEVANCE_TERMS = {
    "retrieval": (
        "retrieval",
        "information retrieval",
        "semantic search",
        "vector search",
        "vector database",
        "hybrid search",
        "dense retrieval",
        "embeddings",
        "embedding drift",
        "index refresh",
        "faiss",
        "pinecone",
        "weaviate",
        "qdrant",
        "milvus",
        "opensearch",
        "elasticsearch",
        "bm25",
        "sentence transformers",
        "sentence-transformers",
        "bge",
        "e5",
    ),
    "ranking": (
        "ranking",
        "ranking system",
        "search ranking",
        "re-ranking",
        "reranking",
        "learning to rank",
        "ltr",
        "relevance",
        "ndcg",
        "mrr",
        "map",
        "precision@",
        "offline benchmark",
        "eval framework",
        "evaluation framework",
    ),
    "recommendation": (
        "recommendation",
        "recommendation system",
        "recommendation systems",
        "recommender",
        "recommender system",
        "personalization",
        "matching system",
        "matching engine",
        "feed ranking",
        "ads ranking",
        "marketplace ranking",
    ),
    "production_ml": (
        "production",
        "deployed",
        "deploy",
        "shipped",
        "launched",
        "real users",
        "latency",
        "scale",
        "scaled",
        "online",
        "serving",
        "pipeline",
        "feature pipeline",
        "inference",
        "experimentation",
        "a/b test",
        "ab test",
    ),
    "python": (
        "python",
        "pytorch",
        "flask",
        "fastapi",
        "pyspark",
        "airflow",
        "mlflow",
        "bentoml",
    ),
    "evaluation": (
        "ndcg",
        "mrr",
        "map",
        "precision",
        "recall",
        "offline benchmark",
        "evaluation framework",
        "eval framework",
        "a/b test",
        "ab test",
        "experiment",
        "experiment",
    ),
    "llm": (
        "llm",
        "llms",
        "rag",
        "lora",
        "qlora",
        "peft",
        "prompt engineering",
        "fine-tuning llms",
        "fine tuning llms",
        "langchain",
        "llamaindex",
    ),
    "cv_speech": (
        "computer vision",
        "object detection",
        "image classification",
        "yolo",
        "diffusion",
        "asr",
        "speech recognition",
        "tts",
        "robotics",
    ),
}

OWNERSHIP_TERMS = (
    "owned",
    "owner",
    "led",
    "drove",
    "designed",
    "architected",
    "built",
    "implemented",
    "launched",
    "improved",
    "optimized",
    "reduced",
    "increased",
    "mentored",
    "cross-functional",
    "stakeholder",
)

HANDS_ON_TERMS = (
    "implemented",
    "built",
    "coded",
    "developed",
    "deployed",
    "debugged",
    "pipeline",
    "service",
    "api",
    "spark",
    "python",
    "model",
    "feature store",
    "index",
    "retrieval",
    "ranking",
)

RESEARCH_TERMS = (
    "research scientist",
    "research engineer",
    "research fellow",
    "postdoc",
    "postdoctoral",
    "academic lab",
    "phd",
)

ARCHITECTURE_ONLY_TERMS = (
    "architect",
    "principal architect",
    "enterprise architect",
)

BEHAVIOR_QUANTILES = {
    "profile_completeness_score": (42.2, 56.8, 71.6, 80.4),
    "recruiter_response_rate": (0.25, 0.44, 0.62, 0.73),
    "avg_response_time_hours": (68.3, 129.9, 193.3, 240.4),
    "notice_period_days": (30.0, 60.0, 90.0, 120.0),
    "search_appearance_30d": (52.0, 105.0, 158.0, 226.0),
    "saved_by_recruiters_30d": (3.0, 7.0, 11.0, 15.0),
    "profile_views_received_30d": (23.0, 45.0, 68.0, 86.0),
    "interview_completion_rate": (0.48, 0.62, 0.76, 0.85),
    "github_activity_score": (14.3, 28.4, 42.3, 51.7),
    "connection_count": (174.0, 335.0, 497.0, 595.0),
    "endorsements_received": (14.0, 28.0, 43.0, 55.0),
}

STAGE7_WEIGHTS = {
    "semantic": 0.58,
    "career": 0.42,
}

